export const LOAD = '@redux-conn/LOAD'
export const LOAD_SUCCESS = '@redux-conn/LOAD_SUCCESS'
export const LOAD_FAIL = '@redux-conn/LOAD_FAIL'
export const CLEAR = '@redux-conn/CLEAR'
export const BEGIN_GLOBAL_LOAD = '@redux-conn/BEGIN_GLOBAL_LOAD'
export const END_GLOBAL_LOAD = '@redux-conn/END_GLOBAL_LOAD'
export const TOKEN_COOKIE_NAME = 'JwtToken'
